---
name: pr-conventional-commit-validation
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          ticket_key_regex: '^PROJECT-\\d{2,5}$'
          custom_labels: '{"feat": "feature", "fix": "fix", "hotfix": "hotfix", docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "chore", "revert": "revert", "wip": "WIP"}'
          add_scope_label: 'true'
